-- DEMO DATA for the Cozumel pilot. Merchants are INVENTED (is_sample=1).
-- Do not load in production; replace with signed merchants.
INSERT INTO merchants(id,destination_id,name,category,lat,lng,hours,status,is_sample) VALUES (1,'cozumel','El Faro Tacos','Restaurant',20.5112,-86.9468,'12:00–22:00','active',1);
INSERT INTO treasure_drops(id,merchant_id,destination_id,title,item,category,emoji,story_text,gps_lat,gps_lng,difficulty,reward_value_usd,is_mystery,kid_friendly,quantity,remaining,fee_usd,status) VALUES (1,1,'cozumel','The Lighthouse Taco','Free fish taco','Food','🌮','Where the old lighthouse keeper ate his supper, the smell of lime and fire still leads the way. Can you find it before another explorer does?',20.5112,-86.9468,'Easy',4,0,1,28,18,28,'active');
INSERT INTO merchants(id,destination_id,name,category,lat,lng,hours,status,is_sample) VALUES (2,'cozumel','Café Azul Malecón','Café',20.5061,-86.9502,'07:00–15:00','active',1);
INSERT INTO treasure_drops(id,merchant_id,destination_id,title,item,category,emoji,story_text,gps_lat,gps_lng,difficulty,reward_value_usd,is_mystery,kid_friendly,quantity,remaining,fee_usd,status) VALUES (2,2,'cozumel','The Captain''s First Cup','Free iced café de olla','Drink','☕','Follow the blue shutters south along the sea wall; the first cup of the day is on the captain.',20.5061,-86.9502,'Easy',3,0,0,35,25,35,'active');
INSERT INTO merchants(id,destination_id,name,category,lat,lng,hours,status,is_sample) VALUES (3,'cozumel','Casa del Cacao Maya','Chocolate shop',20.5041,-86.9471,'10:00–19:00','active',1);
INSERT INTO treasure_drops(id,merchant_id,destination_id,title,item,category,emoji,story_text,gps_lat,gps_lng,difficulty,reward_value_usd,is_mystery,kid_friendly,quantity,remaining,fee_usd,status) VALUES (3,3,'cozumel','The Maya Cacao Trove','Free Mayan chocolate tasting','Dessert','🍫','The Maya paid in beans. Bring nothing but curiosity and leave with a taste of their treasure.',20.5041,-86.9471,'Medium',8,0,1,22,12,22,'active');
INSERT INTO merchants(id,destination_id,name,category,lat,lng,hours,status,is_sample) VALUES (4,'cozumel','Reef Riders Dive Shop','Dive shop',20.4961,-86.9559,'08:00–17:00','active',1);
INSERT INTO treasure_drops(id,merchant_id,destination_id,title,item,category,emoji,story_text,gps_lat,gps_lng,difficulty,reward_value_usd,is_mystery,kid_friendly,quantity,remaining,fee_usd,status) VALUES (4,4,'cozumel','The Reef Explorer''s Kit','Free snorkel gear, 2 hours','Adventure','🤿','Mask, fins and a map of the reef. The fish are already waiting.',20.4961,-86.9559,'Medium',15,0,1,18,8,18,'active');
INSERT INTO merchants(id,destination_id,name,category,lat,lng,hours,status,is_sample) VALUES (5,'cozumel','Coco Helado','Ice cream',20.5121,-86.9511,'11:00–23:00','active',1);
INSERT INTO treasure_drops(id,merchant_id,destination_id,title,item,category,emoji,story_text,gps_lat,gps_lng,difficulty,reward_value_usd,is_mystery,kid_friendly,quantity,remaining,fee_usd,status) VALUES (5,5,'cozumel','Frozen Treasure','Free coconut ice cream scoop','Dessert','🍦','A cold surprise is hidden near the beach. Polly knows where…',20.5121,-86.9511,'Easy',3,0,1,50,40,50,'active');
INSERT INTO merchants(id,destination_id,name,category,lat,lng,hours,status,is_sample) VALUES (6,'cozumel','Isla Scooters','Rentals',20.5152,-86.9431,'08:00–18:00','active',1);
INSERT INTO treasure_drops(id,merchant_id,destination_id,title,item,category,emoji,story_text,gps_lat,gps_lng,difficulty,reward_value_usd,is_mystery,kid_friendly,quantity,remaining,fee_usd,status) VALUES (6,6,'cozumel','The Island Steed','Free first hour of scooter rental','Adventure','🛵','Every hunter needs a ship. This one has two wheels.',20.5152,-86.9431,'Easy',12,0,0,16,6,16,'active');
INSERT INTO merchants(id,destination_id,name,category,lat,lng,hours,status,is_sample) VALUES (7,'cozumel','Tortuga Beach Club','Beach club',20.47,-86.969,'09:00–18:00','active',1);
INSERT INTO treasure_drops(id,merchant_id,destination_id,title,item,category,emoji,story_text,gps_lat,gps_lng,difficulty,reward_value_usd,is_mystery,kid_friendly,quantity,remaining,fee_usd,status) VALUES (7,7,'cozumel','Turtle Cove Lounger','Free lounger + welcome drink','Adventure','🏖️','Head south where the turtles nest. Your sun lounger has your name on it.',20.47,-86.969,'Hard',18,0,1,20,10,20,'active');
INSERT INTO merchants(id,destination_id,name,category,lat,lng,hours,status,is_sample) VALUES (8,'cozumel','Mangle Eco Kayaks','Tours',20.4455,-86.9803,'08:00–16:00','active',1);
INSERT INTO treasure_drops(id,merchant_id,destination_id,title,item,category,emoji,story_text,gps_lat,gps_lng,difficulty,reward_value_usd,is_mystery,kid_friendly,quantity,remaining,fee_usd,status) VALUES (8,8,'cozumel','The Mangrove Passage','Free 1-hour kayak','Adventure','🛶','Paddle through the mangroves at the island''s quiet edge, where maps run out.',20.4455,-86.9803,'Hard',20,0,1,15,5,15,'active');
INSERT INTO merchants(id,destination_id,name,category,lat,lng,hours,status,is_sample) VALUES (9,'cozumel','Galería Sol','Jewelry',20.5098,-86.9447,'10:00–21:00','active',1);
INSERT INTO treasure_drops(id,merchant_id,destination_id,title,item,category,emoji,story_text,gps_lat,gps_lng,difficulty,reward_value_usd,is_mystery,kid_friendly,quantity,remaining,fee_usd,status) VALUES (9,9,'cozumel','The Hidden Jewel','Free sterling silver charm','Mystery','💎','Only true explorers discover this treasure. Look for the sun above a blue door, two streets from the sea.',20.5098,-86.9447,'Medium',10,1,0,19,9,19,'active');
INSERT INTO merchants(id,destination_id,name,category,lat,lng,hours,status,is_sample) VALUES (10,'cozumel','Huaraches Isla','Crafts',20.5075,-86.9459,'09:00–20:00','active',1);
INSERT INTO treasure_drops(id,merchant_id,destination_id,title,item,category,emoji,story_text,gps_lat,gps_lng,difficulty,reward_value_usd,is_mystery,kid_friendly,quantity,remaining,fee_usd,status) VALUES (10,10,'cozumel','The Sandal Maker''s Token','Free handmade leather keychain','Shopping','🛍️','Three generations of sandal makers left a small gift for travelers who wander off the main street.',20.5075,-86.9459,'Easy',6,0,1,32,22,32,'active');
INSERT INTO hunts(destination_id,name,emoji,tagline,starts_on,ends_on,status) VALUES ('cozumel','Pirate Week','🏴‍☠️','Treasures hidden around the island. Every verified find earns credits and a raffle ticket.','2026-09-28','2026-10-04','live'),('cozumel','Dive Week','🤿','Reef treasures for underwater explorers.','2026-10-12','2026-10-18','scheduled'),('cozumel','Día de Muertos Hunt','💀',null,'2026-10-31','2026-11-02','draft');
